/**
 * AI Web Roaster - Roast Toast Content Script
 * Triggers periodic roast pop-ups while scrolling web pages.
 */

(function () {
  'use strict';

  const extApi = typeof browser !== 'undefined' ? browser : (typeof chrome !== 'undefined' ? chrome : null);

  let toastContainerEl = null;
  let roastTimer = null;

  // Default configuration
  let config = {
    roastEnabled: true,
    roastInterval: 300, // seconds (default 10s)
    serverUrl: 'http://localhost:8000/roast'
  };

  // Local fallback roasts if Python server is offline
  const LOCAL_FALLBACK_ROASTS = [
    "That's a lot of corporate buzzwords to say you built an API wrapper with zero revenue. 💀",
    "Reading this page is officially classified as a non-pharmacological sleep aid. 😴",
    "This webpage has more tracking scripts than actual useful content. 🕵️‍♂️",
    "Is this a blog post or a 2000-word SEO recipe preamble nobody asked for? 🍲",
    "This section sounds like it was generated by an AI prompt given zero context. 🤖",
    "Imagine spending 4 paragraphs explaining something that could be answered in 3 words. 📝",
    "Congratulations, you reached the part of the article designed solely to pad the word count! 🎉"
  ];

  /**
   * Load saved settings (defaults to ALWAYS ENABLED) and start auto-roaster
   */
  function initRoaster() {
    console.log('[AI Web Roaster] Auto-roaster active for page:', location.href);

    if (extApi && extApi.storage && extApi.storage.local) {
      extApi.storage.local.get({ roastEnabled: true, roastInterval: 10 }, (res) => {
        config.roastEnabled = res.roastEnabled !== false; // Default TRUE unless explicitly turned off
        config.roastInterval = res.roastInterval || 10;
        restartRoastTimer();
      });
    } else {
      restartRoastTimer();
    }
  }

  /**
   * Restart interval timer based on current config
   */
  function restartRoastTimer() {
    if (roastTimer) clearInterval(roastTimer);

    if (!config.roastEnabled) {
      console.log('[AI Web Roaster] Auto-roast turned OFF in settings.');
      return;
    }

    console.log(`[AI Web Roaster] Running hands-free roaster every ${config.roastInterval} seconds.`);

    // Trigger first roast automatically 1.5 seconds after page loads
    setTimeout(triggerRoast, 1500);

    // Continue triggering automatically on interval
    const intervalMs = Math.max(5, config.roastInterval) * 1000;
    roastTimer = setInterval(triggerRoast, intervalMs);
  }

  /**
   * Fetch roast via Background Service Worker to bypass HTTPS loopback/CORS restrictions
   */
  function triggerRoast() {
    if (!config.roastEnabled) return;

    // Check if extension context is still valid (stops timer if extension was reloaded)
    if (!extApi || !extApi.runtime || !extApi.runtime.id) {
      if (roastTimer) clearInterval(roastTimer);
      return;
    }

    // Get current visible text snippet on page
    const paragraph = getVisibleParagraphSnippet();

    try {
      extApi.runtime.sendMessage({
        action: 'FETCH_ROAST',
        payload: {
          text: paragraph,
          url: location.href
        }
      }, (response) => {
        if (extApi.runtime && extApi.runtime.lastError) {
          console.warn('[AI Web Roaster] Extension context updated. Refreshing page recommended.');
          if (roastTimer) clearInterval(roastTimer);
          return;
        }

        if (response && response.success && response.data && response.data.roast) {
          showToast(response.data.roast);
        } else {
          console.warn('[AI Web Roaster] Background fetch fallback:', response ? response.error : 'No response');
          const randomRoast = LOCAL_FALLBACK_ROASTS[Math.floor(Math.random() * LOCAL_FALLBACK_ROASTS.length)];
          showToast(randomRoast);
        }
      });
    } catch (err) {
      console.warn('[AI Web Roaster] Extension reloaded. Please refresh tab (F5).');
      if (roastTimer) clearInterval(roastTimer);
    }
  }

  /**
   * Extract visible text snippet from ANY webpage or Web App (Google, Canva, Wikipedia, YouTube, etc.)
   */
  function getVisibleParagraphSnippet() {
    // 1. Try visible text elements on screen
    const selectors = 'p, h1, h2, h3, h4, h5, blockquote, article, section, [role="main"], div, span, li, label';
    const elements = Array.from(document.querySelectorAll(selectors));

    for (let el of elements) {
      // Skip our own toast container to prevent self-roasting
      if (el.closest('#ai-roast-toast-container')) continue;

      const text = el.innerText ? el.innerText.trim() : '';
      // Require at least 15 characters of meaningful text
      if (text.length >= 15 && text.length < 2000) {
        const rect = el.getBoundingClientRect();
        // Element is visible in viewport and has visible dimensions
        if (rect.top < window.innerHeight && rect.bottom > 0 && rect.width > 0 && rect.height > 0) {
          return text.substring(0, 300);
        }
      }
    }

    // 2. Fallback for custom Web Apps (Canva, Google Search, Figma, etc.)
    if (document.body && document.body.innerText) {
      const bodyText = document.body.innerText.trim();
      if (bodyText.length > 10) {
        return bodyText.substring(0, 300);
      }
    }

    return document.title || 'Web Application Page';
  }

  /**
   * Ensure Toast Container element exists on DOM
   */
  function ensureContainer() {
    if (!toastContainerEl || !document.body.contains(toastContainerEl)) {
      toastContainerEl = document.createElement('div');
      toastContainerEl.id = 'ai-roast-toast-container';
      document.body.appendChild(toastContainerEl);
    }
  }

  /**
   * Display floating roast toast notification
   */
  function showToast(roastText) {
    ensureContainer();

    const toast = document.createElement('div');
    toast.className = 'ai-roast-toast';

    toast.innerHTML = `
      <div class="ai-roast-toast-header">
        <span class="ai-roast-badge">🔥 AI Roast</span>
        <button class="ai-roast-close-btn" title="Dismiss">✖</button>
      </div>
      <div class="ai-roast-body">${escapeHTML(roastText)}</div>
      <div class="ai-roast-progress-bar"></div>
    `;

    toastContainerEl.appendChild(toast);

    // Trigger CSS slide-in animation
    setTimeout(() => toast.classList.add('show'), 50);

    // Dismiss on close button click
    const closeBtn = toast.querySelector('.ai-roast-close-btn');
    closeBtn.addEventListener('click', () => removeToast(toast));

    // Auto dismiss after 6 seconds
    setTimeout(() => removeToast(toast), 6000);
  }

  /**
   * Remove toast element with smooth animation
   */
  function removeToast(toastEl) {
    if (!toastEl) return;
    toastEl.classList.remove('show');
    setTimeout(() => toastEl.remove(), 400);
  }

  /**
   * Escape HTML to prevent XSS
   */
  function escapeHTML(str) {
    if (!str) return '';
    return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  }

  /**
   * Listen for setting updates from Popup UI
   */
  if (extApi && extApi.runtime && extApi.runtime.onMessage) {
    extApi.runtime.onMessage.addListener((message, sender, sendResponse) => {
      if (message.action === 'UPDATE_ROAST_SETTINGS') {
        config = { ...config, ...message.settings };
        restartRoastTimer();
        if (sendResponse) sendResponse({ status: 'ok' });
      } else if (message.action === 'TRIGGER_MANUAL_ROAST') {
        triggerRoast();
        if (sendResponse) sendResponse({ status: 'ok' });
      }
      return true;
    });
  }

  // Initialize roaster
  initRoaster();

})();
