from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import re
import random
import uvicorn

app = FastAPI(title="AI Web Roaster Backend API")

# Enable CORS for browser extensions (Vivaldi, Firefox, Chrome)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Mock Roast Database (Will be replaced by fine-tuned LLM model inference)
MOCK_ROASTS = [
    "That's a lot of corporate buzzwords to say you built an API wrapper with zero revenue. 💀",
    "Reading this page is officially classified as a non-pharmacological sleep aid. 😴",
    "This webpage has more tracking scripts than actual useful content. 🕵️‍♂️",
    "I've seen cleaner code written in brainfuck than the design layout of this site. 🎨",
    "Is this a blog post or a 2000-word SEO recipe recipe preamble nobody asked for? 🍲",
    "This section sounds like it was generated by an AI prompt that was given zero context. 🤖",
    "Imagine spending 4 paragraphs explaining something that could be answered in a 3-word bullet point. 📝",
    "This page uses so much hype language, even crypto founders are cringing. 🚀",
    "The author wrote this with the confidence of someone who has never been peer-reviewed. 🔬",
    "Congratulations, you reached the part of the article designed solely to pad the word count! 🎉"
]

class RoastRequest(BaseModel):
    text: str = ""
    url: str = ""

@app.get("/")
def root():
    return {"message": "AI Web Roaster API is running!", "status": "online"}

@app.get("/roast")
@app.post("/roast")
def generate_roast(req: RoastRequest = None):
    # Select a random roast (later replaced with model.generate())
    selected_roast = random.choice(MOCK_ROASTS)
    return {
        "roast": selected_roast,
        "source": "python_fastapi_server"
    }

if __name__ == "__main__":
    print("🚀 Starting AI Web Roaster Python Server on http://localhost:8000")
    uvicorn.run(app, host="0.0.0.0", port=8000)
